// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: example.proto

#include "example.pb.h"
#include "example.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace example {

static const char* ResNet_method_names[] = {
  "/example.ResNet/ClassifyImage",
};

std::unique_ptr< ResNet::Stub> ResNet::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ResNet::Stub> stub(new ResNet::Stub(channel));
  return stub;
}

ResNet::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_ClassifyImage_(ResNet_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ResNet::Stub::ClassifyImage(::grpc::ClientContext* context, const ::example::ImageMatrix& request, ::example::ClassifyResult* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ClassifyImage_, context, request, response);
}

void ResNet::Stub::experimental_async::ClassifyImage(::grpc::ClientContext* context, const ::example::ImageMatrix* request, ::example::ClassifyResult* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ClassifyImage_, context, request, response, std::move(f));
}

void ResNet::Stub::experimental_async::ClassifyImage(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::example::ClassifyResult* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ClassifyImage_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::example::ClassifyResult>* ResNet::Stub::AsyncClassifyImageRaw(::grpc::ClientContext* context, const ::example::ImageMatrix& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::example::ClassifyResult>::Create(channel_.get(), cq, rpcmethod_ClassifyImage_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::example::ClassifyResult>* ResNet::Stub::PrepareAsyncClassifyImageRaw(::grpc::ClientContext* context, const ::example::ImageMatrix& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::example::ClassifyResult>::Create(channel_.get(), cq, rpcmethod_ClassifyImage_, context, request, false);
}

ResNet::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ResNet_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ResNet::Service, ::example::ImageMatrix, ::example::ClassifyResult>(
          std::mem_fn(&ResNet::Service::ClassifyImage), this)));
}

ResNet::Service::~Service() {
}

::grpc::Status ResNet::Service::ClassifyImage(::grpc::ServerContext* context, const ::example::ImageMatrix* request, ::example::ClassifyResult* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace example

