// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: example.proto

#include "example.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace example {
class ImageMatrixDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ImageMatrix> _instance;
} _ImageMatrix_default_instance_;
class ClassifyResultDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ClassifyResult> _instance;
} _ClassifyResult_default_instance_;
}  // namespace example
static void InitDefaultsImageMatrix_example_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::example::_ImageMatrix_default_instance_;
    new (ptr) ::example::ImageMatrix();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::example::ImageMatrix::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ImageMatrix_example_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsImageMatrix_example_2eproto}, {}};

static void InitDefaultsClassifyResult_example_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::example::_ClassifyResult_default_instance_;
    new (ptr) ::example::ClassifyResult();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::example::ClassifyResult::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ClassifyResult_example_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsClassifyResult_example_2eproto}, {}};

void InitDefaults_example_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_ImageMatrix_example_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ClassifyResult_example_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_example_2eproto[2];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_example_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_example_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_example_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::example::ImageMatrix, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::example::ImageMatrix, image_matrix_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::example::ClassifyResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::example::ClassifyResult, result_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::example::ImageMatrix)},
  { 6, -1, sizeof(::example::ClassifyResult)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::example::_ImageMatrix_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::example::_ClassifyResult_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_example_2eproto = {
  {}, AddDescriptors_example_2eproto, "example.proto", schemas,
  file_default_instances, TableStruct_example_2eproto::offsets,
  file_level_metadata_example_2eproto, 2, file_level_enum_descriptors_example_2eproto, file_level_service_descriptors_example_2eproto,
};

const char descriptor_table_protodef_example_2eproto[] =
  "\n\rexample.proto\022\007example\"#\n\013ImageMatrix\022"
  "\024\n\014image_matrix\030\001 \003(\005\" \n\016ClassifyResult\022"
  "\016\n\006result\030\001 \001(\0052J\n\006ResNet\022@\n\rClassifyIma"
  "ge\022\024.example.ImageMatrix\032\027.example.Class"
  "ifyResult\"\000b\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_example_2eproto = {
  false, InitDefaults_example_2eproto, 
  descriptor_table_protodef_example_2eproto,
  "example.proto", &assign_descriptors_table_example_2eproto, 179,
};

void AddDescriptors_example_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_example_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_example_2eproto = []() { AddDescriptors_example_2eproto(); return true; }();
namespace example {

// ===================================================================

void ImageMatrix::InitAsDefaultInstance() {
}
class ImageMatrix::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ImageMatrix::kImageMatrixFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ImageMatrix::ImageMatrix()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:example.ImageMatrix)
}
ImageMatrix::ImageMatrix(const ImageMatrix& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      image_matrix_(from.image_matrix_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:example.ImageMatrix)
}

void ImageMatrix::SharedCtor() {
}

ImageMatrix::~ImageMatrix() {
  // @@protoc_insertion_point(destructor:example.ImageMatrix)
  SharedDtor();
}

void ImageMatrix::SharedDtor() {
}

void ImageMatrix::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ImageMatrix& ImageMatrix::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ImageMatrix_example_2eproto.base);
  return *internal_default_instance();
}


void ImageMatrix::Clear() {
// @@protoc_insertion_point(message_clear_start:example.ImageMatrix)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  image_matrix_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ImageMatrix::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ImageMatrix*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // repeated int32 image_matrix = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) == 10) {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::google::protobuf::internal::PackedInt32Parser;
          object = msg->mutable_image_matrix();
          if (size > end - ptr) goto len_delim_till_end;
          auto newend = ptr + size;
          if (size) ptr = parser_till_end(ptr, newend, object, ctx);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr == newend);
          break;
        } else if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        do {
          msg->add_image_matrix(::google::protobuf::internal::ReadVarint(&ptr));
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 8 && (ptr += 1));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ImageMatrix::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:example.ImageMatrix)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 image_matrix = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_image_matrix())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 10u, input, this->mutable_image_matrix())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:example.ImageMatrix)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:example.ImageMatrix)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ImageMatrix::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:example.ImageMatrix)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 image_matrix = 1;
  if (this->image_matrix_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_image_matrix_cached_byte_size_.load(
        std::memory_order_relaxed));
  }
  for (int i = 0, n = this->image_matrix_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->image_matrix(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:example.ImageMatrix)
}

::google::protobuf::uint8* ImageMatrix::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:example.ImageMatrix)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 image_matrix = 1;
  if (this->image_matrix_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        _image_matrix_cached_byte_size_.load(std::memory_order_relaxed),
         target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->image_matrix_, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:example.ImageMatrix)
  return target;
}

size_t ImageMatrix::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:example.ImageMatrix)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 image_matrix = 1;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->image_matrix_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast<::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    _image_matrix_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ImageMatrix::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:example.ImageMatrix)
  GOOGLE_DCHECK_NE(&from, this);
  const ImageMatrix* source =
      ::google::protobuf::DynamicCastToGenerated<ImageMatrix>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:example.ImageMatrix)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:example.ImageMatrix)
    MergeFrom(*source);
  }
}

void ImageMatrix::MergeFrom(const ImageMatrix& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:example.ImageMatrix)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  image_matrix_.MergeFrom(from.image_matrix_);
}

void ImageMatrix::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:example.ImageMatrix)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ImageMatrix::CopyFrom(const ImageMatrix& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:example.ImageMatrix)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ImageMatrix::IsInitialized() const {
  return true;
}

void ImageMatrix::Swap(ImageMatrix* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ImageMatrix::InternalSwap(ImageMatrix* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  image_matrix_.InternalSwap(&other->image_matrix_);
}

::google::protobuf::Metadata ImageMatrix::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_example_2eproto);
  return ::file_level_metadata_example_2eproto[kIndexInFileMessages];
}


// ===================================================================

void ClassifyResult::InitAsDefaultInstance() {
}
class ClassifyResult::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClassifyResult::kResultFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClassifyResult::ClassifyResult()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:example.ClassifyResult)
}
ClassifyResult::ClassifyResult(const ClassifyResult& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  result_ = from.result_;
  // @@protoc_insertion_point(copy_constructor:example.ClassifyResult)
}

void ClassifyResult::SharedCtor() {
  result_ = 0;
}

ClassifyResult::~ClassifyResult() {
  // @@protoc_insertion_point(destructor:example.ClassifyResult)
  SharedDtor();
}

void ClassifyResult::SharedDtor() {
}

void ClassifyResult::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ClassifyResult& ClassifyResult::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ClassifyResult_example_2eproto.base);
  return *internal_default_instance();
}


void ClassifyResult::Clear() {
// @@protoc_insertion_point(message_clear_start:example.ClassifyResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  result_ = 0;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ClassifyResult::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ClassifyResult*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int32 result = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_result(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ClassifyResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:example.ClassifyResult)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 result = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &result_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:example.ClassifyResult)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:example.ClassifyResult)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ClassifyResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:example.ClassifyResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->result() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->result(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:example.ClassifyResult)
}

::google::protobuf::uint8* ClassifyResult::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:example.ClassifyResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->result() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->result(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:example.ClassifyResult)
  return target;
}

size_t ClassifyResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:example.ClassifyResult)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 result = 1;
  if (this->result() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->result());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ClassifyResult::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:example.ClassifyResult)
  GOOGLE_DCHECK_NE(&from, this);
  const ClassifyResult* source =
      ::google::protobuf::DynamicCastToGenerated<ClassifyResult>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:example.ClassifyResult)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:example.ClassifyResult)
    MergeFrom(*source);
  }
}

void ClassifyResult::MergeFrom(const ClassifyResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:example.ClassifyResult)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.result() != 0) {
    set_result(from.result());
  }
}

void ClassifyResult::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:example.ClassifyResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClassifyResult::CopyFrom(const ClassifyResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:example.ClassifyResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClassifyResult::IsInitialized() const {
  return true;
}

void ClassifyResult::Swap(ClassifyResult* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClassifyResult::InternalSwap(ClassifyResult* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(result_, other->result_);
}

::google::protobuf::Metadata ClassifyResult::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_example_2eproto);
  return ::file_level_metadata_example_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace example
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::example::ImageMatrix* Arena::CreateMaybeMessage< ::example::ImageMatrix >(Arena* arena) {
  return Arena::CreateInternal< ::example::ImageMatrix >(arena);
}
template<> PROTOBUF_NOINLINE ::example::ClassifyResult* Arena::CreateMaybeMessage< ::example::ClassifyResult >(Arena* arena) {
  return Arena::CreateInternal< ::example::ClassifyResult >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
